services:
  handbook-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hanbook-application
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-db:5432/handbook"
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    depends_on:
      postgres-db:
        condition: service_healthy

  postgres-db:
    image: postgres:17
    container_name: handbook_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: handbook
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5433:5432'
    volumes:
      - handbook_db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d handbook" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  handbook_db_data:
